name: CI Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout RMatrix
      uses: actions/checkout@v4
    
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make gcc
    
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build --parallel
    
    - name: Run Tests
      run: ctest --test-dir build --output-on-failure
